services:
  streamlit-app:
    build: ./
    command: streamlit run src/main.py --server.port 8501
    image: streamlit-image
    container_name: streamlit-app
    restart: unless-stopped
    ports:
      - 8501:8501
    volumes:
      - ./:/app
